### ISSUE TITLE
hanging on boot/reboot if no network when network is expected

### ISSUE THREAD

**Issue by noon92** [noon92/femtofox#5]
Happens inconsistently.

![image](https://github.com/user-attachments/assets/96d266c8-df10-4791-8926-dae4e18362af)

**Comment by Ruledo** [comment]
Fixed by editing /lib/systemd/system/ifup@.service and lowering the timeout.
File added to addons.

**Comment by noon92** [comment]
Leaving this open for further testing

**Comment by noon92** [comment]
<img width="599" alt="image" src="https://github.com/user-attachments/assets/7a79f2f1-c5b5-4f3d-8271-71666abe8d91">
Still happening, at least on shutdown

**Comment by noon92** [comment]
Seems fixed. Closing for now
